services:
  ###########
  # Backups #
  ###########
  socket-proxy:
      image: linuxserver/socket-proxy:latest
      environment:
        ALLOW_START: 1
        ALLOW_STOP: 1
        CONTAINERS: 1
        EXEC: 1
        POST: 1
        VERSION: 1
      read_only: true
      tmpfs:
        - /run
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
      restart: unless-stopped
      networks:
        - backup
  backup:
    image: ghcr.io/lawndoc/stack-back:latest
    depends_on:
      socket-proxy:
        condition: service_started
    restart: unless-stopped
    environment:
      AUTO_BACKUP_ALL: "true" # auto backup all volumes and databases unless explicitly excluded
      AWS_ACCESS_KEY_ID: ${B2_BUCKET_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${B2_BUCKET_KEY_SECRET}
      DOCKER_HOST: tcp://socket-proxy:2375
      RESTIC_REPOSITORY: ${RESTIC_REPOSITORY}
      RESTIC_PASSWORD: ${RESTIC_BACKUP_PASSWORD}
      RESTIC_KEEP_DAILY: 7
      RESTIC_KEEP_WEEKLY: 4
      RESTIC_KEEP_MONTHLY: 12
      RESTIC_KEEP_YEARLY: 3
      CRON_SCHEDULE: "0 2 * * *"
      DISCORD_WEBHOOK: ${STACKBACK_DISCORD_WEBHOOK}
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - backupcache:/cache
    networks:
      - backup
    healthcheck:
      test: ["CMD", "rcb", "status"]
      interval: 30m
      timeout: 5m
      retries: 3
      start_period: 1m
  ##############
  # Monitoring #
  ##############
  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    labels:
      - "stack-back.volumes=false" # disable volume backups for this container
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      # - /mnt/disk/.beszel:/extra-filesystems/sda1:ro
    environment:
      PORT: 45876
      KEY: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE9n246QELTB365/0kEXp8e0g1/jVsGep6kc0tQGEvJE"
    healthcheck:
      test: ['CMD', '/agent', 'health']
      interval: 120s
volumes:
  backupcache:
networks:
  backup:
